(function($){$.fn.toSVG=function(options){var params=$.extend({svgClass:"replaced-svg",onComplete:function(){},},options)
this.each(function(){var $img=jQuery(this);var imgID=$img.attr('id');var imgClass=$img.attr('class');var imgURL=$img.attr('src');if(!(/\.(svg)$/i.test(imgURL))){return;}
$.get(imgURL,function(data){var $svg=jQuery(data).find('svg');if(typeof imgID!=='undefined'){$svg=$svg.attr('id',imgID);}
if(typeof imgClass!=='undefined'){$svg=$svg.attr('class',imgClass+params.svgClass);}
$svg=$svg.removeAttr('xmlns:a');if(!$svg.attr('viewBox')&&$svg.attr('height')&&$svg.attr('width')){$svg.attr('viewBox','0 0 '+$svg.attr('height')+' '+$svg.attr('width'))}
$img.replaceWith($svg);typeof params.onComplete=="function"?params.onComplete.call(this,$svg):'';})});}})(jQuery);$(document).ready(function(){var w=screen.width;var h=screen.height;var bw=window.innerWidth;var bh=window.innerHeight;var headerHeight=$(".header").outerHeight();$('img.svg-js').toSVG();$('.lang_chooser select[name="lang"]').on('change',function(e){var ths=$(this),thsVal=ths.val(),windowLocation=window.location.href;if(windowLocation!==thsVal){window.location=thsVal;}
console.log(thsVal,windowLocation);});$(".form_send").each(function(){var it=$(this);it.validate({rules:{phone:{required:true}},messages:{},errorPlacement:function(error,element){},submitHandler:function(form){var thisForm=$(form);$.ajax({type:"POST",url:thisForm.attr("action"),data:thisForm.serialize()}).done(function(){$.fancybox.close();$.fancybox.open({src:'#modalThanks',touch:false,baseClass:'thanks_message',openEffect:"elastic",openMethod:"zoomIn",closeEffect:"elastic",closeMethod:"zoomOut",});setTimeout(function(){$.fancybox.close();},3000);$(".focus_field__element").removeClass('focused');it.trigger("reset");});return false;},success:function(){},highlight:function(element,errorClass){$(element).addClass('error');},unhighlight:function(element,errorClass,validClass){$(element).removeClass('error');}})});$(".scroll_btn").click(function(){var id=$(this).attr('href');var topOffset=$(id).attr("data-top");var top=$(id).offset().top;var finalTop;if(typeof topOffset!==typeof undefined&&topOffset!==false){finalTop=top-topOffset;}else{finalTop=top;}
$('body,html').animate({scrollTop:finalTop},700);event.preventDefault();});var header=$(".header");var tempScrollTop=0;var currentScrollTopLoad=$(document).scrollTop();if(currentScrollTopLoad<1){header.removeClass("moved");}else{header.addClass("moved");}
if(w>767){$(window).scroll(function(){var currentScrollTop=$(document).scrollTop();if(currentScrollTop<1){header.removeClass("moved");}else{header.addClass("moved");}});}
$(".fancybox").fancybox({touch:false,baseClass:"gal_frame",});$(".video_btn").fancybox({baseClass:"wrap_video",});$(".modal").fancybox({closeBtn:false,smallBtn:false,buttons:[],touch:false,hideScrollbar:false,});$(".modal_close").click(function(event){$.fancybox.close();});$('.slider_item').slick();$('.o_fit').objectFit({objectFit:'cover',objectPosition:'center',replaceElement:'<div />',replaceClass:'o_fit_replaced'});$('select').selectric({disableOnMobile:false,nativeOnMobile:false,maxHeight:150,onOpen:function(){$(this).closest('.select_wrapper').addClass('opened');$(this).parent().next().next().find(".selectric-scroll").mCustomScrollbar({theme:"my-theme"});},onClose:function(){$(this).closest('.select_wrapper').removeClass('opened');}}).on('change',function(){$(this).closest(".select_wrapper").addClass('changed').attr("data-value",$(this).val());});$(".focus_field__element").focus(function(event){var th=$(this);th.addClass('focused');});$(".focus_field__element").blur(function(event){var th=$(this);if(th.val().length<1){th.removeClass('focused');}});$(".scroll_block").mCustomScrollbar({theme:"my-theme"});$("body").on('click','a',function(event){if($(this).attr('href')=="#"||$(this).attr('href')==""){event.preventDefault();}});$(".tabs").on('click','.tab_link',function(event){event.stopPropagation();var th=$(this),parent=th.attr("data-parent"),activeTab=th.attr("data-tab");if(!th.hasClass('active')){th.closest(parent).find(".tabs_list .tab_link[data-parent='"+parent+"']").removeClass("active");th.closest(parent).find(".tabs_list .tab_link[data-tab='"+activeTab+"']").addClass("active");if(activeTab=='all'){th.closest(parent).find('.tab_content[data-parent="'+parent+'"]').fadeIn();if($('.tab_content[data-parent="'+parent+'"]').find(".slick-slider").length>0){$('.tab_content[data-parent="'+parent+'"]').find(".slick-slider").slick("setPosition");}}else{th.closest(parent).find('.tab_content[data-parent="'+parent+'"]').hide();th.closest(parent).find("#"+activeTab).fadeIn();if($('.tab_content[data-parent="'+parent+'"]').find(".slick-slider").length>0){$('.tab_content[data-parent="'+parent+'"]').find(".slick-slider").slick("setPosition");}}}else{}});$("section").on('click','.tab_heading',function(event){event.stopPropagation();var th=$(this),parent=th.attr("data-parent"),activeTab=th.attr("data-tab");if($(parent).find(activeTab).is(':hidden')){th.closest(parent).find('.tab_content[data-parent="'+parent+'"]').slideUp();$(parent).find(activeTab).slideDown();th.closest(parent).find(".tabs_list .tab_link[data-tab='"+activeTab.substring(1)+"']").addClass("active").siblings().removeClass('active');}else{th.closest(parent).find('.tab_content[data-parent="'+parent+'"]').slideUp();}
event.preventDefault();});$("textarea").on('keyup',function(event){autosize($(this));});$(".hidden_trigger").click(function(event){event.preventDefault();var th=$(this),trget=th.attr("href");$(trget).slideToggle();th.toggleClass('open_menu');});$("[data-hover-color]").mouseover(function(){$(this).css('color',$(this).attr('data-hover-color'));}).mouseout(function(){$(this).css('color',$(this).attr('data-hover-default'));});$(".header_contact").on('click',function(event){event.preventDefault();if(window.innerWidth<768){var th=$(this),thTarget=th.attr('href');$.fancybox.open({src:thTarget,touch:false});}else{return false;}});$(".header_contact_dropdown_close").on('click',function(event){event.preventDefault();$.fancybox.close();});});$(window).on('load',function(){if($(".map_block").length){mapBuilder();}});$(window).on('load resize',function(){var w=screen.width;var h=screen.height;var bw=window.innerWidth;var bh=window.innerHeight;var headerHeight=$(".header").outerHeight();if(bw>767){if($(".full_screen_section_js").length){var nfSection=$(".full_screen_section_js");nfSection.css('minHeight',bh-headerHeight);}}
if($(".prperty_items").length){hBlock($(".section-business-server"),$(".pi_body:not(.pi_body_large)"))}
if($(".wps_blocks").length){hBlock($(".section-vps"),$(".wps_block__body_text_content"))
hBlock($(".section-vps"),$(".wps_block__top_table"))}
if($(".adw_screen_frame_blocks").length){hBlock($(".section-advantages"),$(".adw_screen_frame_block_top"))}});function autosize(ths){var el=ths;setTimeout(function(){el.css('height',el.prop('scrollHeight')+'px');},10);}
function hBlock(section,selector){var max=0;var itemsSelector=selector,sectionWrapper=section;itemsSelector.removeAttr('style');sectionWrapper.each(function(index,el){$(this).find(itemsSelector).each(function(){var h=$(this).innerHeight();max=h>max?h:max;});$(this).find(itemsSelector).css('minHeight',(max+1)+'px');});}
function mapBuilder(){var stylers=[{"stylers":[{"saturation":-100},{"gamma":1}]},{"elementType":"labels.text.stroke","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.business","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.text","stylers":[{"visibility":"off"}]},{"featureType":"poi.place_of_worship","elementType":"labels.icon","stylers":[{"visibility":"off"}]},{"featureType":"road","elementType":"geometry","stylers":[{"visibility":"simplified"}]},{"featureType":"water","stylers":[{"visibility":"on"},{"saturation":50},{"gamma":0},{"hue":"#50a5d1"}]},{"featureType":"administrative.neighborhood","elementType":"labels.text.fill","stylers":[{"color":"#333333"}]},{"featureType":"road.local","elementType":"labels.text","stylers":[{"weight":0.5},{"color":"#333333"}]},{"featureType":"transit.station","elementType":"labels.icon","stylers":[{"gamma":1},{"saturation":50}]}];if($("#map1").length>0){var mapElement=document.getElementById('map1'),map1Latitude=mapElement.getAttribute('data-latitude'),map1Longtitude=mapElement.getAttribute('data-longitude'),pin=mapElement.getAttribute('data-pin');var pin2Latitude=$(".map_contol").eq(1).attr('data-controll-lat'),pin2Longtitude=$(".map_contol").eq(1).attr('data-controll-longt');console.log(pin2Latitude);console.log(pin2Longtitude);var mapOptions={center:new google.maps.LatLng(map1Latitude,map1Longtitude),zoom:14,zoomControl:true,zoomControlOptions:{style:google.maps.ZoomControlStyle.DEFAULT,},disableDoubleClickZoom:true,mapTypeControl:false,mapTypeControlOptions:{style:google.maps.MapTypeControlStyle.HORIZONTAL_BAR,},scaleControl:false,scrollwheel:false,panControl:false,streetViewControl:false,draggable:true,overviewMapControl:false,fullscreenControl:false,overviewMapControlOptions:{opened:false,},mapTypeId:google.maps.MapTypeId.ROADMAP,styles:stylers}
var sb_map=new google.maps.Map(mapElement,mapOptions);var locations=[['','undefined','undefined','undefined','undefined',map1Latitude,map1Longtitude,pin],['','undefined','undefined','undefined','undefined',pin2Latitude,pin2Longtitude,pin],];for(i=0;i<locations.length;i++){if(locations[i][1]=='undefined'){description='';}else{description=locations[i][1];}
if(locations[i][2]=='undefined'){telephone='';}else{telephone=locations[i][2];}
if(locations[i][3]=='undefined'){email='';}else{email=locations[i][3];}
if(locations[i][4]=='undefined'){web='';}else{web=locations[i][4];}
if(locations[i][7]=='undefined'){markericon='';}else{markericon=locations[i][7];}
marker=new google.maps.Marker({icon:markericon,position:new google.maps.LatLng(locations[i][5],locations[i][6]),map:sb_map,title:locations[i][0],desc:description,tel:telephone,email:email,web:web});link='';}
$(".map_contols").on('click','.map_contol',function(event){event.preventDefault();var th=$(this),thLat=parseFloat(th.attr('data-controll-lat')),thLongt=parseFloat(th.attr('data-controll-longt'));sb_map.setCenter({lat:thLat,lng:thLongt});th.addClass('active').siblings().removeClass('active');});}}